### ISSUE TITLE
Build failed: build zydis as a dynamic link library on MacOS

### ISSUE THREAD

**Issue by yszhou2019** [zyantific/zydis#350] opened 2022-06-20 03:55 UTC
OS: macOS 12.4 Monterey
CPU: 2 GHz 4 core Intel Core i5
Compiler:
Homebrew clang version 13.0.0
Target: x86_64-apple-darwin21.5.0
Thread model: posix
cxxflags:
-DZYDIS_BUILD_SHARED_LIB=ON
-DCMAKE_POSITION_INDEPENDENT_CODE=ON

When i build zydis with shared flag, the problem I've encounted is as follows.

> ld: warning: pointer not aligned at address 0x77DEA (_STR_MNEMONIC + 15786 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77DE1 (_STR_MNEMONIC + 15777 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77DCF (_STR_MNEMONIC + 15759 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77DC6 (_STR_MNEMONIC + 15750 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77DBD (_STR_MNEMONIC + 15741 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77DAB (_STR_MNEMONIC + 15723 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77DA2 (_STR_MNEMONIC + 15714 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D99 (_STR_MNEMONIC + 15705 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D87 (_STR_MNEMONIC + 15687 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D7E (_STR_MNEMONIC + 15678 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D75 (_STR_MNEMONIC + 15669 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D63 (_STR_MNEMONIC + 15651 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D5A (_STR_MNEMONIC + 15642 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D51 (_STR_MNEMONIC + 15633 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D3F (_STR_MNEMONIC + 15615 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D36 (_STR_MNEMONIC + 15606 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x77D2D (_STR_MNEMONIC + 15597 from CMakeFiles/Zydis.dir/src/Mnemonic.c.o)
> ld: warning: pointer not aligned at address 0x79329 (_STR_SIZE_8_INTEL + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x79332 (_STR_SIZE_16_INTEL + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x7933B (_STR_SIZE_32_INTEL + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x7934D (_STR_SIZE_64_INTEL + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x79356 (_STR_SIZE_80 + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x7935F (_STR_SIZE_128_INTEL + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x79371 (_STR_SIZE_512_INTEL + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x7937A (_STR_ADDR_RELATIVE + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x79383 (_ZydisStringAppendDecS.str_add + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x79395 (_ZydisStringAppendHexS.str_add + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: warning: pointer not aligned at address 0x7939E (_ZydisStringAppendHexS.str_sub + 0 from CMakeFiles/Zydis.dir/src/FormatterIntel.c.o)
> ld: unaligned pointer(s) for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [libZydis.3.2.1.0.dylib] Error 1
> make[1]: *** [CMakeFiles/Zydis.dir/all] Error 2
> make: *** [all] Error 2

**Comment by flobernd** [comment] 2022-06-20 06:31
@athre0z Could you check please? From my quick search it seems to be a common issue with Clang 13 (at least a breaking change).

**Comment by athre0z** [comment] 2022-06-20 11:11
This is already fixed on master (https://github.com/zyantific/zydis/pull/259), but we never back-ported it to `v3.x`. I'll see if I can find some time for that later.

**Comment by athre0z** [comment] 2022-06-20 11:14
Actually I just noticed that our code checks for aarch64 as architecture, and OP is encountering this issue on a X86 box. Looks like Apple ported this linker issue to X86 now & we'll have to adjust the check. 🙃

**Comment by athre0z** [comment] 2023-10-01 16:15
It looks like Zydis builds just fine targeting AMD64 macOS. I don't have an Intel Mac anymore and thus can't test this on bare metal, but at least in Rosetta it builds just fine. 

I'm pretty sure that I remember there being some temporary bugs surrounding pointer alignment on Intel in one version of the macOS toolchain, and I'm suspecting that this was the cause of this.

I'll close this for the moment. If you (or anyone else) runs into this again with latest toolchain, please feel free to re-open.

**Comment by JamesAldridge** [comment] 2024-01-16 08:44
Seems to be the same issue

System Specifications:

Operating System: macOS Sonoma 14.1 (23B74)
CPU: 2.7 GHz Quad-Core Intel Core i7
Compiler Info:
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: x86_64-apple-darwin23.1.0
Thread model: posix

When i build zydis with shared flag, the problem I've encountered is as follows.

`Jamess-MacBook-Pro-4:jak-project-v-update-zydis jamesaldridge$ cmake --build build --parallel $((`sysctl -n hw.logicalcpu`))
[0/2] Re-checking globbed directories...
[2/11] Linking C shared library third-party/zydis/libZydis.4.0.0.0.dylib
FAILED: third-party/zydis/libZydis.4.0.0.0.dylib
: && /usr/bin/clang -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 4.0.0 -current_version 4.0.0 -o third-party/zydis/libZydis.4.0.0.0.dylib -install_name @rpath/libZydis.4.0.dylib third-party/zydis/CMakeFiles/Zydis.dir/src/MetaInfo.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Register.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Segment.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/SharedData.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/String.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Utils.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Zydis.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Decoder.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/DecoderData.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Encoder.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/EncoderData.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Disassembler.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/Formatter.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterBuffer.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterATT.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterBase.c.o third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterIntel.c.o  third-party/zydis/zycore/libZycore.a && :
ld: warning: pointer not aligned at _STR_MNEMONIC+0x9 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x12 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x1B from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x24 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x2D from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x36 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x3F from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x51 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x5A from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x63 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x6C from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x75 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x7E from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x87 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0x99 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0xA2 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0xAB from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0xB4 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o
ld: warning: pointer not aligned at _STR_MNEMONIC+0xBD from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/Mnemonic.c.o

ld: warning: pointer not aligned at _STR_PREF_REX_4E+0x0 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterBase.c.o
ld: warning: pointer not aligned at _STR_PREF_REX_4F+0x0 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterBase.c.o
ld: warning: pointer not aligned at _STR_ADD+0x0 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterIntel.c.o
ld: warning: pointer not aligned at _STR_MUL+0x0 from /Users/jamesaldridge/dev/jak-project-v-update-zydis/build/third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterIntel.c.o
ld: pointer not 4-byte aligned at __DATA_CONST+0x39, fix alignment or disable chained fixups
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.`

**Comment by athre0z** [comment] 2024-01-16 17:09
Ah, I see that you created a separate issue -- I'll close again and we can continue the discussion in that one.

**Closed by athre0z** 2024-01-16 17:09 UTC
Labels: C-bug, P-medium, A-build
