### ISSUE TITLE
hello, when support assembler?

### ISSUE THREAD

**Issue by DiskGetor** [zyantific/zydis#145] opened 2020-05-20 11:32 UTC

**Comment by BullyWiiPlaza** [comment] 2020-05-25 11:13
+1

I feel like most other assembler projects aren't quite as user-friendly and neat as `Zydis`.

**Comment by athre0z** [comment] 2020-05-25 11:24
I'm going to close this because it is pretty much a duplicate of #129, however given the name that the other issue previously had (I renamed it now) it really isn't surprising at all that you didn't find it.

Yes, having an encoder would be great. Unfortunately, it is a pretty brutal amount of work. I'd say if we wanted to support the whole ISA with all exts, calculating in testing and debugging and then even more testing, this will take at least two weeks of full time work, perhaps more.

This has been on our agenda since day 1, but we just never came around to putting in the work required.

**Closed by athre0z** 2020-05-25 11:24 UTC
