### ISSUE TITLE
MinGW "windows.h" include bug

### ISSUE THREAD

**Issue by sccoouut** [zyantific/zydis#213] opened 2021-09-04 09:19 UTC
MinGW requires a lower-case "windows.h" include. In "examples/ZydisPerfTest.c", it's started with capital letter, could you fix it please?

**Comment by athre0z** [comment] 2021-09-04 10:18
Fixed in 861187e28920bb4a10d98d53f21d77ceadcd6eda, thanks for letting us know!

**Comment by flobernd** [comment] 2021-09-04 10:33
Probably related to #128. Could be that Zycore needs a fix as well.

**Comment by athre0z** [comment] 2021-09-04 11:14
Yes, but it's the inverse problem. This issue with build failure in MinGW came up a few years ago and we decided to switch all `Windows.h` includes to lowercase. The occurrence in this example was simply a regression. I grepped through both Zycore and Zydis and all other includes seem to be lowercase already.

WDK builds, for some reason, apparently require the uppercase variant. This is the reason why the WDK build is now apparently broken for some people. I'm unsure whether we actually ever verified that or not -- I'm still hypothesizing that the user in the issue might have been building on a case-sensitive filesystem.

**Closed by athre0z** 2021-09-04 11:14 UTC
Labels: C-bug, P-medium, A-examples

**Comment by flobernd** [comment] 2021-09-04 11:19
> I'm unsure whether we actually ever verified that or not

I remember testing this on Windows, so it's rather a general issue with the WDDK. But I think you are right and it was a different issue anyways. There either was no `windows.h` at all or the code uses user-mode APIs which I need to change to their kernel-mode couterparts.

**Comment by athre0z** [comment] 2021-09-04 11:20
Yeah, makes sense.
