### ISSUE TITLE
Sign bit on imm8 causes use of 16-bit push in encoder

### ISSUE THREAD

**Issue by duk-37** [zyantific/zydis#330] opened 2022-04-24 15:57 UTC
This code will use a 16-bit push instead of a 32-bit one, causing breakage. Note that not using the 8-bit short form is correct behavior because of sign extension.

```cpp
ZydisEncoderRequest req = {};
req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
req.mnemonic = ZYDIS_MNEMONIC_PUSH;
req.operand_count = 1;

// this works
// req.operand_size_hint = ZYDIS_OPERAND_SIZE_HINT_64;

req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE;
req.operands[0].imm.u = 0x80;

ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH] = {};
ZyanUSize encoded_length = sizeof(encoded_instruction);
ZydisEncoderEncodeInstruction(&req, encoded_instruction, &encoded_length);

for (size_t i = 0; i < encoded_length; ++i)
{
	printf("%02X ", encoded_instruction[i]);
}
```

**Comment by mappzor** [comment] 2022-04-29 10:29
I can't reproduce this. Are you sure you are running on the latest version?

This is old behavior, in the past it was the expected one. Encoder would always try to generate smallest possible code when no hint was provided. To make things more intuitive for vast majority of use cases I reworked it, so `ZYDIS_OPERAND_SIZE_HINT_NONE` works as "native" operand size instead of "smallest possible".

**Comment by athre0z** [comment] 2022-04-29 11:52
Oh yeah true, it indeed doesn't ocurr master. @duk-37 had asked me to confirm the problem before creating this issue and I reproduced it, however not realizing that I also had an outdated source-tree on the machine I was on then. I guess we can close this then! :)

**Closed by athre0z** 2022-04-29 11:52 UTC
Labels: C-bug, P-medium, A-encoder
