### ISSUE TITLE
LNK2019 error on vs2019 x86 kernel mode driver

### ISSUE THREAD

**Issue by Kwansy98** [zyantific/zydis#344] opened 2022-05-28 03:04 UTC
I got a link error on x86 debug mode like this: 1>main.obj : error LNK2019: 无法解析的外部符号 __imp__ZydisDecoderInit@12，函数 _DriverEntry@8 中引用了该符号
But every thing work fine when i use x64 mode.
Zydis installed from vcpkg and i test it in console mode program which has no problem.

**Comment by athre0z** [comment] 2022-06-12 14:54
Linker errors are generally related incorrect project configuration. Please make sure to correctly link against `Zydis.lib`. I also don't really know how vcpkg works on Windows, but I suspect that it will pre-build the static library and not pass the required arguments for kernel-mode builds on Windows. The library it builds will thus likely not work correctly when linked into a kernel mode project.

Regardless, this is not a bug on our side, so I'll close this issue.

**Closed by athre0z** 2022-06-12 14:54 UTC
