### ISSUE TITLE
ZydisWinKernel  fatal error: 'windows.h' file not found

### ISSUE THREAD

**Issue by taodaqiao** [zyantific/zydis#128] opened 2020-01-14 10:35 UTC
vs2017 15.9.18 Compile Zydis v3.0.0 kernel Zycore cannot open include file: "windows.h"

**Comment by flobernd** [comment] 2020-01-14 16:27
@athre0z 
Looks like this commit was not so great in retro: https://github.com/zyantific/zycore-c/commit/594709398f086eaead286f44e50903929358ed90

**Comment by athre0z** [comment] 2020-01-14 16:31
@taodaqiao Are you building this on a case-sensitive network drive, by any chance?

**Comment by taodaqiao** [comment] 2020-01-14 16:34
@athre0z Not a case problem, Zycore doesn't support the kernel?

**Comment by athre0z** [comment] 2020-01-14 16:41
We do support Windows kernel builds and if this doesn't work, this is a bug -- no need to close the issue! 

The problem appears to be that we use lower-case `windows.h` because this is required by MinGW builds and MSVC (VS compiler) and Windows in general usually don't care about casing. That's why I was asking whether you were building / have your DDK installation on a network drive that cares about casing, because that would explain the issue.

@flobernd Any chance that you could try to reproduce that?

**Comment by taodaqiao** [comment] 2020-01-14 16:43
![image](https://user-images.githubusercontent.com/33372680/72363556-07615a80-3730-11ea-9ed9-9a62373318c1.png)
WindowsKernelModeDriver10.0   no problem

**Comment by taodaqiao** [comment] 2020-01-14 16:46
@athre0z 1>Building 'Zycore' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
1>Terminal.c
1>e:\c library\zydis\dependencies\zycore\src\api\terminal.c(32,13): error C1083:  : “windows.h”: No such file or directory
1>e:\c library\zydis\dependencies\zycore\src\api\terminal.c(32,13): error C1083: #   include <windows.h
1>e:\c library\zydis\dependencies\zycore\src\api\terminal.c(32,13): error C1083:

**Comment by flobernd** [comment] 2020-01-15 11:24
Ok I investigated the problem and it seems like `Zydis` builds fine but the `Zycore` dependency currently does not.

I created an issue here: https://github.com/zyantific/zycore-c/issues/19.

For now you could just remove all `.c` files from the `Zycore` project as `Zydis` uses only the `.h` files of `Zycore` anyways.

**Closed** 2021-09-05 17:33 UTC
Labels: C-bug, P-medium, A-msvc
